### ISSUE TITLE
There is no .exe???

### ISSUE THREAD

**Issue by Rainbowpanda2020** [millefoleon/BloonTowerMaker#17]
I downloaded the zip file then extracted it but i searched all the files without finding an exe

**Comment by TheBusinessPyro** [comment]
its a rar file by the name of towermaker.rar go to releases
https://github.com/millefoleon/BloonTowerMaker/releases/download/Alpha/TowerMaker.rar here is the download

**Comment by Rainbowpanda2020** [comment]
how do i open it after that

**Comment by TheBusinessPyro** [comment]
extract it with 7zip, and then open the exe called bloontowermaker.exe

**Comment by Rainbowpanda2020** [comment]
Thanks!
