### ISSUE TITLE
Cant compile tower

### ISSUE THREAD

**Issue by YeloPik404** [millefoleon/BloonTowerMaker#19]
When i try to compile my tower it gives me this error message that i don't understand what i have to do. My first one seemed to compile alright (but glitched my game) but the others didn't i compared my first one's code to the others and filled out the code that the first one had that the others didn't but it still doesn't work.

![Capture2](https://user-images.githubusercontent.com/103423571/162725399-894a79a5-1ee0-47c5-b6bb-7b3f8d662b28.PNG)

**Comment by TheBusinessPyro** [comment]
try removing your projectiles and see if it works, projectiles dont work after a few something (dont know the proper word to use)

**Comment by TheBusinessPyro** [comment]
How did you put upgrade and that 000 picture?
I didnt figure how

**Comment by YeloPik404** [comment]
Does not work, just adds another error. (Also to add the pictures just tap the portrait or whatever and click on the three grey boxes from the bottom and then choose what picture you want to put in)

**Comment by TheBusinessPyro** [comment]
do you have the required boxes?
DisplayName, Cost, Description.
and DisplayName, Cost, Description for upgrade paths

**Comment by sm64onlydude** [comment]
> Does not work, just adds another error. (Also to add the pictures just tap the portrait or whatever and click on the three grey boxes from the bottom and then choose what picture you want to put in)

Can ye take a pic or video to where it is, still cant find it

**Comment by TheBusinessPyro** [comment]
do you mind taking a pic of ur tower stats screen? mind doesnt show the 3 grey boxes

**Comment by TheBusinessPyro** [comment]
mine looks like 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/74529728/162862979-775a79fc-db06-4cc0-8dc6-271564644339.png">

**Comment by YeloPik404** [comment]
well That is weird maybe try putting it on full screen or something. But anyways here is the picture
![Capture3](https://user-images.githubusercontent.com/103423571/162918144-83032136-7f56-4048-b054-20675b11ed00.PNG)

**Comment by YeloPik404** [comment]
well now that i have seen your code i used it to correct and fix my first one's code and then i was able to copy and paste and edit it the file for the potato gunner. It may have taken a long time but at least in the end i have done what i desired for and i now declare this issue closed. (you just need to make sure that your author name, project name and anything else that relates to a name should not have any spaces as that what causes this error.)
