### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by modderongithub** [millefoleon/BloonTowerMaker#2]
No matter what I try, it simply doesn't compile the mod.

**Comment by leonyarov** [comment]
Please provide a screenshot of the error

**Comment by modderongithub** [comment]
![scrnshot](https://user-images.githubusercontent.com/71789415/156898375-f9335953-98e6-400e-a6ca-254cde2340e1.PNG)

**Comment by modderongithub** [comment]
Had it uninstalled waiting for a bugfix before this, reinstalled and threw together this tower that should compile (has a basetower so should grab from it), refuses to compile

**Comment by leonyarov** [comment]
Looks like you are trying to set the ID field. My test showed that this field cannot be set. Please remove any data in the 'id' field.

**Comment by modderongithub** [comment]
Alright, will try

**Comment by modderongithub** [comment]
Seems to work now, thank you.
