### ISSUE TITLE
How to open?

### ISSUE THREAD

**Issue by gratalat** [millefoleon/BloonTowerMaker#21]
This may sound dumb, but I don't know how to open the initial editor.

**Comment by TheBusinessPyro** [comment]
open the exe, make a tower by putting on the required items, and then click on the big blue box on the left to put up the 000 tower editor part

**Comment by gratalat** [comment]
> 
![image](https://user-images.githubusercontent.com/103841996/163913121-08b5282b-3a00-4eea-a94c-2e4aa3193836.png)

Hi! I can't find an exe file anywhere in the file. I downloaded it from Code > Download as zip.

**Comment by TheBusinessPyro** [comment]
wrong download, go to releases thats on the right side of the code tab in github

**Comment by gratalat** [comment]
Omg I am so dumb XD

**Comment by gratalat** [comment]
Wait that's a rar file not an exe 
![image](https://user-images.githubusercontent.com/103841996/164118802-d6a906a8-1115-492a-9f58-98809618d023.png)

**Comment by TheBusinessPyro** [comment]
extract it with 7zip as windows cannot open rar files

**Comment by gratalat** [comment]
Alright. Thank you so much dude.

**Comment by Behemot123** [comment]
Co mam zrobic skoro nie moge rozpakowac go  w 7zip

**Comment by Behemot123** [comment]
Jak włączyc ten edytor?

**Comment by gratalat** [comment]
> Jak włączyc ten edytor?

I didnt figure it out either

**Comment by Behemot123** [comment]
to wiesz co i jak z tym edytorem? pengiunmodder

**Comment by gratalat** [comment]
Ja też nie wiem

**Comment by gratalat** [comment]
nvm i was using 7zip wrong

**Comment by Behemot123** [comment]
ok thank you information , but is there any other program in which you can create your own towers for bloons tower defense 6 as a mod

**Comment by gratalat** [comment]
> ok thank you information , but is there any other program in which you can create your own towers for bloons tower defense 6 as a mod

no
