### ISSUE TITLE
Suggestion: Make the guide more explanatory, or example folder.

### ISSUE THREAD

**Issue by gh-doot** [millefoleon/BloonTowerMaker#22]
I love the concept of this mod, giving the ability for beginners with no coding experience to make their own mods, but though, the guide seems to not be always fully helpful, and may make me and other beginners completely confused;

I have 2 solutions that could possibly fix this small problem;
1. Make a example folder to give beginners a better understanding of the application
2. Improve the guide to cover everything about the application so that beginners can get the full concept.

I hope you will look at this problem and fix this, looking forward to your next update.

**Comment by leonyarov** [comment]
Hi! 
Thank you for sharing your opinion on this software!
I highly value your suggestion, and I understand that many of you struggle with the way the UI is built. 
You all deserve better, and the next update will bring a complete redesign of the UI and the way you design towers.
As no other similar kind of software exists in the modding community, developing this project is a hard and time consuming task (at least while I'm solo).
There is much for me to learn on how to use Mod Helper and other libraries but I'm getting to the point I understand  the process of developing mods for this game.
I can't tell you the exact release date but please be sure that I'm working on it. 
Stay positive!

**Comment by gh-doot** [comment]
Thank you so much for the reply! Again, looking forward to your updates!

**Comment by gratalat** [comment]
> 

Can you look at my thread? It's weird, even after getting the .exe file, it won't work properly. I'm on windows 11 btw.

**Comment by gratalat** [comment]
> 

@millefoleon
